---
- name: get consul-alerts
  sudo: yes
  get_url:
    url: https://bintray.com/artifact/download/darkcrux/generic/consul-alerts-latest-linux-amd64.tar
    dest: /tmp/consul-alerts.tar
    sha256sum: b4c46245f6e30bbad28ba21d17a39fa8cd489ed3478cff32d5e7945510a84155
    mode: 0755
  tags:
    - consul-alerts

- name: unarchive consul-alerts
  sudo: yes
  unarchive:
    copy: no
    creates: /usr/local/bin/consul-alerts
    src: /tmp/consul-alerts.tar
    dest: /usr/local/bin
    group: root
    owner: root
    mode: 0755

- name: configure consul-alerts service
  sudo: yes
  template:
    src: consul-alerts.service.j2
    dest: /usr/lib/systemd/system/consul-alerts.service
  notify:
    - reload consul-alerts
  tags:
    - consul-alerts

- name: configure notifications
  sudo: yes
  run_once: yes
  command: consul-cli kv-write consul-alerts/config/notifiers/{{ item.key }} {{ item.value }}
  with_items: consul_alerts_notifiers
  notify:
    - restart consul-alerts
  tags:
    - consul-alerts

- name: enable consul-alerts
  sudo: yes
  service:
    name: consul-alerts
    enabled: yes
    state: started
  tags:
    - consul-alerts